[theme]
base="dark"
primaryColor="#564592"
backgroundColor="#564592"
secondaryBackgroundColor="#E1DEEF"
textColor="#F2F0FA"
linkColor = "#EDF67D"
linkUnderline = false
codeBackgroundColor = "#ecebe4"
font="sans serif"
baseRadius = "3rem"