[theme]
base="dark"
primaryColor="#564592"
backgroundColor="#564592"
secondaryBackgroundColor="#724cf9"
textColor="#F2F0FA"
linkColor = "#EDF67D"
linkUnderline = false
codeBackgroundColor = "#564592"
font="sans serif"
baseRadius = "3rem"