[theme]
base="light"
primaryColor="#564592"
backgroundColor="#564592"
secondaryBackgroundColor="#E3DACC"
textColor="#3D3A2A"
linkColor = "#EDF67D"
linkUnderline = false
codeBackgroundColor = "#ecebe4"
font="sans serif"
baseRadius = "3rem"